name: "Create app release"
description: |
  Create a new app release on a local "releases" branch
inputs:

  message:
    description: Extra message to add to the release commit message, eg. closes ABC-123, closes ABC-567
    required: false

runs:
  using: composite
  steps:
  - name: Source branch
    uses: actions/checkout@v4
    with:
      path: source

  - name: History checkout (without trees and blobs)
    uses: actions/checkout@v4
    with:
      fetch-depth: 0 # History for changelog
      filter: tree:0
      path: history

  - name: Checkout releases branch
    uses: actions/checkout@v4
    id: checkout-releases-branch
    continue-on-error: true
    with:
      path: releases
      ref: "releases"

  - name: Get last release commit
    uses: actions/github-script@v7
    id: last-release-commit
    with:
      script: |
        const fs = require("fs");

        const currentCommitSha = process.env.GITHUB_SHA

        let gitLogRange = currentCommitSha

        try {
          const metadata = JSON.parse(fs.readFileSync("./releases/release.json", "utf8"));

          gitLogRange = `${metadata.commitId}..${currentCommitSha}`
        } catch (e) {
          console.error(`Error reading releases/release.json`, e);
        }

        core.setOutput("git-log-range", gitLogRange);
        core.summary.addRaw(`Git changelog range: \`${gitLogRange}\``).write();

  - name: Generate git-log.txt
    shell: bash
    working-directory: history
    run: |
      git log "${{ steps.last-release-commit.outputs.git-log-range }}" > ../git-log.txt

  - name: Start releases branch from current branch, if not exists
    if: steps.checkout-releases-branch.outcome == 'failure'
    uses: actions/checkout@v4
    with:
      path: releases

  - name: Create release
    shell: bash
    working-directory: source
    run: |
      export TZ="Europe/Copenhagen"
      node "${{ github.action_path }}/create-app-release.js"

  - name: Release version
    uses: actions/github-script@v7
    id: release-version
    with:
      script: |
        const fs = require("fs");

        const appJson = JSON.parse(fs.readFileSync("./source/app.json", "utf8"));

        core.setOutput("version", appJson.expo.version);

        // Setup release metadata
        const commitId = process.env.GITHUB_SHA;

        fs.writeFileSync("./source/release.json", JSON.stringify({commitId}, null, 2));

        core.summary
          .addRaw(`Release version: \`${appJson.expo.version}\``)
          .write()

  - name: Create destination dir for new release commit
    shell: bash
    run: |
      cp -r source destination
      rm -rf destination/.git
      cp -r releases/.git destination/.git

  - name: Setup git user info
    shell: bash
    working-directory: source
    run: |
      set -eou pipefail

      git_author="$(git show -s HEAD --format='%an')" || exit 1
      git_author_email="$(git show -s HEAD --format='%ae')" || exit 1

      echo "git author: \"${git_author}\""
      echo "git author email: \"${git_author_email}\""

      git config --global user.name "$git_author"
      git config --global user.email "$git_author_email"

      git config push.default current

  - name: Generate commit message.txt
    working-directory: destination
    shell: bash
    run: |
      echo "${{ steps.release-version.outputs.version }} " > ../message.txt
      echo >> ../message.txt

      echo "${{ inputs.message }}" >> ../message.txt

      echo >> ../message.txt

      echo "author-commit-id: ${{ github.sha }}" >> ../message.txt
      echo >> ../message.txt

      cat ../git-log.txt >> ../message.txt

  - name: Commit & push changes
    uses: actions/github-script@v7
    with:
      script: |
        process.chdir("./destination");

        // Try creating the branch (for first time)
        await exec.exec("git", ["switch", "-c", "releases"], { silent: true, ignoreReturnCode: true });

        await exec.exec("git", ["add", "."]);

        // Test for changes
        const hasChanges = await exec.exec("git", ["diff-index", "--quiet", "HEAD"], { silent: true, ignoreReturnCode: true });

        if (!hasChanges) {
          console.log("No changes to commit");
          return;
        }

        const currentReleaseCommitShaResult = await exec.getExecOutput("git", ["rev-parse", "HEAD"]);
        const currentReleaseCommitSha = currentReleaseCommitShaResult.stdout.trim();

        // Fetch top of current branch to allow referencing current build commit as parent on releases branch
        await exec.exec("git", ["fetch", "--depth=1", "origin", process.env.GITHUB_REF]);

        const newTreeResult = await exec.getExecOutput("git", ["write-tree"]);
        const newTreeId = newTreeResult.stdout.trim();

        const newCommitShaResult = await exec.getExecOutput("git", ["commit-tree", newTreeId, "-F", "../message.txt", "-p", currentReleaseCommitSha, "-p", process.env.GITHUB_SHA]);

        const newCommitSha = newCommitShaResult.stdout.trim();

        await exec.exec("git", ["reset", "--hard", newCommitSha]);

        const branches = {
          releases: "releases",
        }

        // # Push branch (for first time)
        await exec.exec("git", ["push", "-u", "origin", branches.releases], { silent: true, ignoreReturnCode: true });

        for (let n = 1; n <= 5; n++) {
          let pushSuccess = false;

          try {
            await exec.exec("git", ["pull", "origin", branches.releases, "--rebase"] );
            await exec.exec("git", ["push", "origin", branches.releases]);
            pushSuccess = true;
          } catch (e) {
            console.log(`Error sync'ing ${branches.releases} branch`, e);
          }

          if (pushSuccess) {
            break;
          }

          if (n === 5) {
            throw new Error(`Failed to push after 5 attempts`);
          }

          console.log(`Failed to push, attempt ${n}`);
          await new Promise(resolve => setTimeout(resolve, n * 1000));
        }

        // Tag source branch for visibility (GITHUB_SHA commit is available from fetch)
        const version = ${{ toJSON(steps.release-version.outputs.version) }};
        const tagName = `v${version}`;

        await exec.exec("git", ["tag", "-a", tagName, process.env.GITHUB_SHA, "-F", "../message.txt"]);

        await exec.exec("git", ["push", "origin", tagName]);
