name: 'Docker build & push To Digital Ocean'
description: 'Build docker image and push to digital ocean registry'
inputs:
  ssh-private-key:
    description: 'SSH Private Key'
    required: true
  digital-ocean-access-token:
    description: 'Digital Ocean Access Token'
    required: true
  image:
    description: 'Docker tag'
    required: true
  directory:
    description: 'Where to build the image from'
    required: false
    default: './'
runs:
  using: "composite"
  steps:
    - uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - uses: crazy-max/ghaction-github-runtime@v2

    - name: Build image
      shell: bash
      working-directory: ${{ inputs.directory }}
      env:
        DOCKER_BUILDKIT: "1"
      run: |
        docker buildx create --use --driver=docker-container
        docker buildx build \
          --file Dockerfile \
          --tag ${{ inputs.image }} \
          --ssh default \
          --cache-to type=gha,scope=${{ github.ref_name }}-${{ inputs.directory }} \
          --cache-from type=gha,scope=${{ github.ref_name }}-${{ inputs.directory }} \
          .

    - name: Install doctl # install the doctl on the runner
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.digital-ocean-access-token }}

    - name: Push image
      shell: bash
      env:
        DOCKER_BUILDKIT: "1"
      run: |
        doctl registry login
        DOCKER_BUILDKIT=1 docker push ${{ inputs.image }}

